// Main types index file
// This file exports all types from the organized structure

// Centralized interfaces
export * from './interfaces';

// Categorized types
export * from './auth';
export * from './entities';

// Legacy type exports (for backward compatibility)
export * from './api.types';
export * from './common.types';
export * from './navbar.types';

// Re-export specific types that might be used directly
export type { 
  User, 
  UserBasic, 
  UserPreferences, 
  UserSecurity, 
  UserRoles,
  Workspace,
  WorkspaceMember,
  WorkspaceSettings,
  Space,
  SpaceMember,
  SpacePermissions,
  SpaceSettings,
  SpaceStats,
  Board,
  BoardMember,
  BoardSettings,
  BoardTag,
  Column,
  ColumnTask,
  ColumnSettings,
  ColumnStyle,
  ColumnStats,
  Task,
  TimeEntry,
  TaskDependency,
  AISuggestions,
  RetentionPolicy,
  Comment,
  CommentReaction,
  File,
  Tag,
  ChatMessage,
  ChatAttachment,
  ChatParticipant,
  Chat,
  Template,
  TemplateItem,
  Notification,
  ActivityItem,
  ActivityUser
} from './interfaces/entities';

export type {
  ApiError,
  ApiRequestConfig,
  ApiEndpoint,
  ApiResponse,
  PaginatedResponse,
  LoginCredentials,
  RegisterData,
  AuthResponse,
  DeviceInfo,
  OAuthUserData,
  OAuthLoginData,
  OAuthCallbackData,
  EmailVerificationData,
  ResendVerificationData,
  PasswordResetRequestData,
  PasswordResetData,
  CreateTaskForm,
  UpdateTaskForm,
  MoveTaskForm,
  CreateBoardForm,
  UpdateBoardForm,
  CreateColumnForm,
  UpdateColumnForm,
  CreateSpaceForm,
  UpdateSpaceForm,
  CreateWorkspaceData,
  UpdateWorkspaceData,
  InviteMemberData,
  SendMessageRequest,
  CreateChatRequest,
  TemplatesFilters
} from './interfaces/api';

export type {
  LoadingState,
  ModalState,
  Theme,
  UserPreferences as CommonUserPreferences,
  Permission,
  WorkspaceRole,
  RouteConfig,
  NavigationItem,
  NavbarConfig,
  BaseComponentProps,
  ModalProps,
  FormFieldProps,
  ValidationResult,
  Attachment,
  TimeRange,
  DateFilter,
  SearchFilters,
  PaginationParams,
  PaginationMeta,
  ErrorBoundaryState,
  ErrorBoundaryProps,
  AccessibilityState,
  PerformanceMetrics,
  AnalyticsEvent,
  LocalizationConfig,
  StorageConfig,
  CacheConfig,
  LogLevel,
  LogEntry
} from './interfaces/common';

export type {
  BaseFormData,
  FormValidation,
  FormState,
  TaskFormData,
  TaskFormValidation,
  BoardFormData,
  BoardFormSettings,
  BoardFormValidation,
  ColumnFormData,
  ColumnFormSettings,
  ColumnFormStyle,
  ColumnFormValidation,
  SpaceFormData,
  SpaceFormSettings,
  SpaceFormValidation,
  WorkspaceFormData,
  WorkspaceFormSettings,
  WorkspaceFormValidation,
  UserProfileFormData,
  UserPreferencesFormData,
  UserProfileFormValidation,
  CommentFormData,
  CommentFormValidation,
  SearchFormData,
  SearchFiltersFormData,
  TemplateFormData,
  TemplateFormValidation,
  InvitationFormData,
  InvitationFormValidation,
  FileUploadFormData,
  FileUploadFormValidation
} from './interfaces/forms';

export type {
  BaseState,
  PaginatedState,
  AuthState,
  UserState,
  WorkspaceState,
  SpaceState,
  BoardState,
  ColumnState,
  TaskState,
  TaskFilters,
  NotificationState,
  NotificationStats,
  TemplatesState,
  PermissionState,
  ActivityState,
  ChatState,
  UIState,
  FormState as StateFormState,
  SocketState,
  SocketNamespaceState,
  FilterState,
  SelectionState,
  LoadingState as StateLoadingState,
  CacheState,
  ErrorState,
  AnalyticsState,
  SettingsState
} from './interfaces/state';

export type {
  BaseUIProps,
  BaseInputProps,
  ButtonProps,
  IconButtonProps,
  TextInputProps,
  TextareaProps,
  SelectProps,
  SelectOption,
  CheckboxProps,
  RadioProps,
  SwitchProps,
  FormProps,
  FormFieldProps,
  FormSectionProps,
  ModalProps,
  ModalHeaderProps,
  ModalBodyProps,
  ModalFooterProps,
  CardProps,
  CardHeaderProps,
  CardBodyProps,
  CardFooterProps,
  TableProps,
  TableColumn,
  TableRowProps,
  NavigationProps,
  NavigationItem,
  BreadcrumbProps,
  BreadcrumbItem,
  LayoutProps,
  HeaderProps,
  SidebarProps,
  BadgeProps,
  AvatarProps,
  TooltipProps,
  PopoverProps,
  AlertProps,
  ToastProps,
  ProgressProps,
  SkeletonProps,
  OverlayProps,
  DrawerProps,
  DropdownProps,
  DropdownItem,
  PortalProps,
  FocusTrapProps,
  ClickOutsideProps
} from './interfaces/ui';

export type {
  SocketNamespace,
  SocketContextType,
  SocketEvent,
  SocketMessage,
  SocketEventData,
  TaskSocketEvent,
  TaskCreatedEvent,
  TaskUpdatedEvent,
  TaskDeletedEvent,
  TaskMovedEvent,
  ColumnSocketEvent,
  ColumnCreatedEvent,
  ColumnUpdatedEvent,
  ColumnDeletedEvent,
  ColumnsReorderedEvent,
  BoardSocketEvent,
  BoardCreatedEvent,
  BoardUpdatedEvent,
  BoardDeletedEvent,
  BoardArchivedEvent,
  SpaceSocketEvent,
  SpaceCreatedEvent,
  SpaceUpdatedEvent,
  SpaceDeletedEvent,
  SpaceArchivedEvent,
  WorkspaceSocketEvent,
  WorkspaceCreatedEvent,
  WorkspaceUpdatedEvent,
  WorkspaceDeletedEvent,
  MemberAddedEvent,
  MemberRemovedEvent,
  MemberRoleChangedEvent,
  CommentSocketEvent,
  CommentCreatedEvent,
  CommentUpdatedEvent,
  CommentDeletedEvent,
  CommentReactionEvent,
  NotificationSocketEvent,
  NotificationCreatedEvent,
  NotificationUpdatedEvent,
  NotificationDeletedEvent,
  NotificationReadEvent,
  ChatSocketEvent,
  MessageCreatedEvent,
  MessageUpdatedEvent,
  MessageDeletedEvent,
  TypingEvent,
  UserJoinedEvent,
  UserLeftEvent,
  SystemSocketEvent,
  SystemStatusEvent,
  MaintenanceModeEvent,
  BackupCompletedEvent,
  ErrorLoggedEvent,
  UserPresenceEvent,
  RoomEvent,
  ConnectionEvent,
  AuthEvent,
  SocketNamespaceConfig,
  SocketEventHandler,
  SocketConnectionStatus,
  SocketMetrics
} from './interfaces/socket';